### ISSUE TITLE
Panasoinic CF-53

### ISSUE THREAD

**Issue by BADJACK80** [BenjaminRenz/QuantumMinigolf2.0#1]
Hallo BenjaminRenz. Ich habe leider keine Möglichkeit gefunden wie man Ihnen innerhalb von Github schreiben kann. Ich habe [hier](https://gist.github.com/en4rab/550880c099b5194fbbf3039e3c8ab6fd#file-cf-u1-bios-md) gesehen das sie ein CF-53 haben welches auch mit einem Passwort versehen war. Ich habe auch ein CF-53 welches mit Biospassworts versehen ist. Könnten Sie mir ein bisschen Unterstützung geben dieses herauszufinden?

**Comment by BenjaminRenz** [comment]
Gerne, schreiben Sie mir einfach eine Mail an appswert (ät) gmail.com
Bräuchte ein wenig Informationen woran es hängt. Ansonsten ginge auch einfach ein Komentar unter [en4rab/CF-U1-BIOS.md](https://gist.github.com/en4rab/550880c099b5194fbbf3039e3c8ab6fd), bekomme dann eine Email-Benachrichtigung, dauert bei Github machmal.
